#!/usr/bin/env bash

source "$HOME/Singularis/bin/common"
source "$HOME/Singularis/bin/variables"

log_info "Installing neomutt"

install_config "NeoMutt" "$CONFIG/neomutt" "$CONFIG_LOCATION/neomutt"
