#!/usr/bin/env bash

source "$HOME/Singularis/bin/common"
source "$HOME/Singularis/bin/variables"

log_info "Installing Better Discord"

install_config "Better Discord" "$CONFIG/BetterDiscord" "$CONFIG_LOCATION/BetterDiscord"
