#!/usr/bin/bash

source "${HOME}/Singularis/bin/common"
source "${HOME}/Singularis/bin/variables"

config_name=${1}
config_location="${CONFIG}/${config_name}"
describe_file="${config_location}/describe.txt"
script_file="${config_location}/script"

mkdir ${config_location}
touch ${script_file} ${describe_file}
chmod +x ${script_file}

echo "#!/usr/bin/env bash

source \"\${HOME}/Singularis/bin/common\"
source \"\${HOME}/Singularis/bin/variables\"

log_info \"Installing ${config_name}\"

ln -sf \"\${CONFIG}/${config_name}\" \"\${CONFIG_LOCATION}\"
" >> ${script_file}

read -p "Describe the config: " description
echo ${description} >> ${describe_file}
