#!/usr/bin/env bash

source bin/common
source bin/variables

if [[ ${1} == '' ]]; then
  log_warn "Are you sure you want to move everything from ${RED}${CONFIG_LOCATION}${RESET} to ${RED}${BACKUP_LOCATION}${RESET}?"
  read -p "[y/n] " clarification
  
  if [[ ${clarification} == 'y' ]]; then
    mv ${CONFIG_LOCATION}/* ${BACKUP_LOCATION}
  else
    exit 1
  fi
elif [[ ${1} == '--help' ]]; then
  log_info "This script moves all of your config files, which are located at ${RED}${CONFIG_LOCATION}${RESET} to ${RED}${BACKUP_LOCATION}${RESET}."
  log_info "If to you want, you can specify what you want to backup, or run ${BLUE}--show${RESET} to see what is there to backup."
  exit 1
elif [[ ${1} == '--show' ]]; then
  for folder in `ls ${CONFIG_LOCATION}/`; do
    log_info ${folder}
  done
  exit 1
else
  for arg in ${@} ; do
    for folder in `ls ${CONFIG_LOCATION}/` ; do
      if [[ ${folder} == ${arg} ]]; then
        mv ${CONFIG_LOCATION}/${arg} ${BACKUP_LOCATION}/
        echo ${CONFIG_LOCATION}
        echo ${arg}
        echo ${BACKUP_LOCATION}
      fi
    done
  done
fi

