#!/usr/bin/env bash

source bin/common
source bin/variables

if [[ ${1} == '' ]]; then
  log_warn "Are you sure you want to move everything from ${RED}${BACKUP_LOCATION}${RESET} to ${RED}${CONFIG_LOCATION}${RESET}."
  read -p "[y/n] " clarification
  
  if [[ ${clarification} == 'y' ]]; then
    mv ${BACKUP_LOCATION}/* ${CONFIG_LOCATION}
  else
    exit 1
  fi
elif [[ ${1} == '--help' ]]; then
  log_info "This script brings back your old configuration, which is stored in ${RED}${BACKUP_LOCATION}${RESET} to ${RED}${CONFIG_LOCATION}${RESET}.\nIf you want, you can specify what you want to uninstall, or run ${BLUE}--show${RESET} to see what is there to bring back."
  exit 1
elif [[ ${1} == '--show' ]]; then
  for folder in `ls ${BACKUP_LOCATION}/`; do
    log_info ${folder}
  done
  exit 1
else
  for arg in ${@} ; do
    for folder in `ls ${BACKUP_LOCATION}/` ; do
      if [[ ${arg} == ${folder} ]]; then
        mv ${BACKUP_LOCATION}/${arg} ${CONFIG_LOCATION}
      fi
    done
  done

  exit 1
fi

