#!/usr/bin/env bash

source ~/Singularis/bin/common
source ~/Singularis/bin/variables

log_info "Installing wal"

ln -sf ${ASPECTS}/wal ~/.config

log_info "Syncing templates"

ln -sf ~/.cache/wal/custom-rofi.rasi ~/.config/rofi/config.rasi
ln -sf ~/.cache/wal/dunstrc ~/.config/dunst/dunstrc
ln -sf ~/.cache/wal/glava_bars.glsl ~/.config/glava/glava_bars.glsl
ln -sf ~/.cache/wal/glava_circle.glsl ~/.config/glava/glava_circle.glsl
ln -sf ~/.cache/wal/glava_graph.glsl ~/.config/glava/glava_graph.glsl
ln -sf ~/.cache/wal/glava_main.glsl ~/.config/glava/glava_main.glsl
ln -sf ~/.cache/wal/glava_radial.glsl ~/.config/glava/glava_radial.glsl
ln -sf ~/.cache/wal/glava_wave.glsl ~/.config/glava/glava_wave.glsl
ln -sf ~/.cache/wal/matplotlibrc ~/.config/matplotlib/matplotlibrc
ln -sf ~/.cache/wal/zathurarc ~/.config/zathura/zathurarc
ln -sf ~/.cache/wal/xmenu-config.h ~/.config/xmenu/colors-xmenu.h
