oomoxicons:
  command: "oomox-archdroid-icons-cli /opt/oomox/scripted_colors/xresources/xresources-reverse"
  name: "Oomix Icons"

oomoxgtk:
  command: "oomox-cli /opt/oomox/scripted_colors/xresources/xresources-reverse"
  name: "Oomix GTK"

oomoxspotify:
  command: "oomoxify-cli /opt/spotify/Apps/.cache/wal/colors-oomox -s"
  name: "Oomix Spotify"

# slickpywal:
#   path: ""
#   command: ""
#   name: ""

# pywalneopixels:
#   path: ""
#   command: ""
#   name: ""

# razercli:
#   path: ""
#   command: ""
#   name: ""

# telegrampalletegen:
#   path: ""
#   command: ""
#   name: ""

pywalfox:
  command: "pywalfox update"
  name: "Firefox"

wal-discord:
  path: "/home/singularis/.local/bin"
  command:
    - "wal-discord"
    - "beautifuldiscord --css /home/singularis/.cache/wal-discord/style.css"
  name: "Discord"

xmenu:
  path: "/home/singularis/.config/xmenu"
  command: "sudo make clean install"
  name: "XMenu"
