oomoxicons:
  arguments: "oomox-archdroid-icons-cli /opt/oomox/scripted_colors/xresources/xresources-reverse"

oomoxgtk:
  arguments: "oomox-cli /opt/oomox/scripted_colors/xresources/xresources-reverse"

oomoxspotify:
  arguments: "oomoxify-cli /opt/spotify/Apps/.cache/wal/colors-oomox -s"

# slickpywal:
#   path: ""
#   config_path: ""
#   executable: ""
#   arguments: ""

# pywalneopixels:
#   path: ""
#   config_path: ""
#   executable: ""
#   arguments: ""

# razercli:
#   path: ""
#   config_path: ""
#   executable: ""
#   arguments: ""

# telegrampalletegen:
#   path: ""
#   config_path: ""
#   executable: ""
#   arguments: ""

pywalfox:
  arguments: "pywalfox update"

wal-discord:
  path: "/home/singularis/.local/bin"
  executable: "wal-discord"
  arguments: "beautifuldiscord --css ~/.cache/wal-discord/style.css"

xmenu:
  path: "/home/singularis/.config/xmenu"
  arguments: "sudo make clean install"

starttree:
  path: "/home/singularis/.local/share/Singularis/third-party-tools/start-tree"

gnuplot:
  path: "/home/singularis/.local/share/Singularis/third-party-tools/gnuplot-pywal"

xfce4-terminal:
  path: "/home/singularis/.local/share/Singularis/third-party-tools/chameleon/scripts"
  config_path: "/home/singularis/.config/xfce4/terminal/terminalrc"
  executable: "./xfce4-terminal.sh"
