#!/usr/bin/env bash

source "$HOME/Singularis/bin/common"
source "$HOME/Singularis/bin/variables"

log_info "Installing spicetify"

install_config "Spicetify" "$CONFIG/spicetify" "$CONFIG_LOCATION/spicetify"
