local servers = {
  emmet_ls = { require("plugins.lsp.settings.emmet_ls"), install = true },
  jsonls = require("plugins.lsp.settings.jsonls"),
  pyright = require("plugins.lsp.settings.pyright"),
  rust_analyzer = require("plugins.lsp.settings.rust_analyzer"),
  solang = require("plugins.lsp.settings.solang"),
  solc = require("plugins.lsp.settings.solc"),
  lua_ls = require("plugins.lsp.settings.lua_ls"),
  cssmodules_ls = { filetypes = { "css" }, install = true },
  -- ltex = require("plugins.lsp.settings.ltex"),
  tsserver = require("plugins.lsp.settings.tsserver"),
  yamlls = require("plugins.lsp.settings.yamlls"),
  sqlls = require("plugins.lsp.settings.sqlls"),
  cssls = { install = true },
  html = require("plugins.lsp.settings.html"),
  texlab = require("plugins.lsp.settings.texlab"),
  bashls = { install = true },
  clangd = require("plugins.lsp.settings.clangd"),
  tailwindcss = { install = true },
  golangci_lint_ls = { install = true },
  jdtls = { install = true },
  solidity_ls = { install = true, install_server_name = "solidity" },
  r_language_server = { install = false },
}

return servers
