#!/usr/bin/env bash

source "${HOME}/Singularis/bin/common"
source "${HOME}/Singularis/bin/variables"

log_info "Installing X"

ln -sf "${CONFIG}/dotfiles/files/.xprofile" 		          "${HOME}"

log_info "Installing zsh"

ln -sf "${CONFIG}/dotfiles/files/zsh"  			              "${CONFIG_LOCATION}"
ln -sf "${CONFIG}/dotfiles/files/.zshrc" 		              "${HOME}"

log_info "Installing tmux"

mkdir -p ~/.config/tmux
ln -sf "${CONFIG}/dotfiles/files/.tmux.conf" 		          "${HOME}"
ln -sf "${CONFIG}/dotfiles/files/..tmux.digests"          "${CONFIG_LOCATION}/tmux"

log_info "Installing env"

ln -sf "${CONFIG}/dotfiles/files/env" 			              "${CONFIG_LOCATION}"

log_info "Installing github email handles"

ln -sf "${CONFIG}/dotfiles/files/.github-handles.json" 	  "${HOME}"
