require("navigator").setup({
  debug = false,
  width = 0.75,
  height = 0.3,
  preview_height = 0.35,
  border = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" },
  ts_fold = false,
  default_mapping = false,
  treesitter_analysis = true,
  treesitter_analysis_max_num = 100,
  treesitter_analysis_condense = true,
  transparency = 50,
  lsp_signature_help = true,
  signature_help_cfg = nil,
  lsp_installer = false,
  mason = false,
  lsp = {
    enable = true,
    disable_lsp = "all",
    code_action = { enable = true, sign = true, sign_priority = 40, virtual_text = true },
    code_lens_action = { enable = true, sign = true, sign_priority = 40, virtual_text = true },
    document_highlight = true,
    format_on_save = false,
    diagnostic = {
      underline = true,
      virtual_text = false,
      update_in_insert = false,
    },
  }
})
