#!/usr/bin/env bash

source "$HOME/Singularis/bin/common"
source "$HOME/Singularis/bin/variables"

log_info "Installing castero"

install_config "Castero" "$CONFIG/castero" "$CONFIG_LOCATION/castero"
