-- local dap = require("dap")
-- local mason_path = vim.fn.glob(vim.fn.stdpath("data")) .. "/mason/"
-- local codelldb_exec_path = mason_path .. "packages/codelldb/codelldb"

-- dap.adapters.codelldb = {
--   type = "server",
--   port = "${port}",
--   executable = {
--     command = codelldb_exec_path,
--     args = { "--port", "${port}" },
--   },
-- }

-- dap.configurations.c = {
--   {
--     name = "Launch",
--     type = "codelldb",
--     request = "launch",
--     -- repl_lang = "c",
--     program = function()
--       return vim.fn.input("Path to executable: ", vim.fn.getcwd() .. "/", "file")
--     end,
--     cwd = "${workspaceFolder}",
--     stopOnEntry = false,
--     args = {},
--   },
-- }
