#!/usr/bin/env bash

source "$HOME/Singularis/bin/common"
source "$HOME/Singularis/bin/variables"

log_info "Installing gnuplot"

install_config "GnuPlot" "$CONFIG/gnuplot" "$CONFIG_LOCATION/gnuplot"
