#!/usr/bin/env bash

source "$HOME/Singularis/bin/common"
source "$HOME/Singularis/bin/variables"

log_info "Installing ncmpcpp"

install_config "NcmpCPP" "$CONFIG/ncmpcpp" "$CONFIG_LOCATION/ncmpcpp"
