location_of_source_code: /home/hashem/System-Theme

oomoxicons:
  # This changes depending on your iconset
  command: "oomox-archdroid-icons-cli"
  # Path to the desired theme you want to apply
  themepath: "/opt/oomox/scripted_colors/xresources/xresources-reverse"

oomoxgtk:
  # Path to the desired theme you want to apply
  themepath: "/opt/oomox/scripted_colors/xresources/xresources-reverse"

# oomoxspotify:
#   spotifypath: "/opt/spotify/Apps"
#   enabled: "True"

# slickpywal:
  # path:

# pywalneopixels:
  # path:

waldiscord:
  path: "/home/hashem/Singularis/third-party-tools/wal-discord"

# razer-cli:
  # path:

telegrampalletegen:
  path: "/home/hashem/Singularis/third-party-tools/telegram-palette-gen"

# spicetify:
  # path:

# pywalfox:
  # path:

starttree:
  path: "/home/hashem/Singularis/third-party-tools/start-tree"

gnuplot:
  path: "/home/hashem/Singularis/third-party-tools/gnuplot-pywal"
