#!/usr/bin/env bash

source "$HOME/Singularis/bin/common"
source "$HOME/Singularis/bin/variables"

wal_cache_loc="$HOME/.cache/wal"

log_info "Installing wal"

install_config "Wal" "$CONFIG/wal" "$CONFIG_LOCATION/wal"

log_info "Syncing templates"

mkdir -p "$CONFIG_LOCATION/rofi"
mkdir -p "$CONFIG_LOCATION/dunst"
mkdir -p "$CONFIG_LOCATION/glava"
mkdir -p "$CONFIG_LOCATION/matplotlib"
mkdir -p "$CONFIG_LOCATION/xmenu"
mkdir -p "$CONFIG_LOCATION/wal-discord"
mkdir -p "$CONFIG_LOCATION/zathura"

install_config "XResources" "$wal_cache_loc/colors.Xresources" "$HOME/.Xresources"
install_config "Rofi" "$wal_cache_loc/custom-rofi.rasi" "$CONFIG_LOCATION/rofi/config.rasi"
install_config "Dunst" "$wal_cache_loc/dunstrc" "$CONFIG_LOCATION/dunst/dunstrc"
install_config "Glava Bars" "$wal_cache_loc/glava_bars.glsl" "$CONFIG_LOCATION/glava/glava_bars.glsl"
install_config "Glava Circle" "$wal_cache_loc/glava_circle.glsl" "$CONFIG_LOCATION/glava/glava_circle.glsl"
install_config "Glava Graph" "$wal_cache_loc/glava_graph.glsl" "$CONFIG_LOCATION/glava/glava_graph.glsl"
install_config "Glava Main" "$wal_cache_loc/glava_main.glsl" "$CONFIG_LOCATION/glava/glava_main.glsl"
install_config "Glava Radial" "$wal_cache_loc/glava_radial.glsl" "$CONFIG_LOCATION/glava/glava_radial.glsl"
install_config "Glava Wave" "$wal_cache_loc/glava_wave.glsl" "$CONFIG_LOCATION/glava/glava_wave.glsl"
install_config "Matplotlib" "$wal_cache_loc/matplotlibrc" "$CONFIG_LOCATION/matplotlib/matplotlibrc"
install_config "Zathura" "$wal_cache_loc/zathurarc" "$CONFIG_LOCATION/zathura/zathurarc"
install_config "XMenu" "$wal_cache_loc/xmenu-config.h" "$CONFIG_LOCATION/xmenu/colors-xmenu.h"
install_config "Colors" "$wal_cache_loc/colors.scss" "$CONFIG_LOCATION/wal-discord/colors.scss"
