#!/usr/bin/env bash

source "${HOME}/Singularis/bin/common"
source "${HOME}/Singularis/bin/variables"

log_info "Installing wal"

ln -sf "${CONFIG}/wal" "${CONFIG_LOCATION}"

log_info "Syncing templates"

wal_cache_loc="${HOME}/.cache/wal"

mkdir -p "${CONFIG_LOCATION}/rofi"
mkdir -p "${CONFIG_LOCATION}/dunst"
mkdir -p "${CONFIG_LOCATION}/glava"
mkdir -p "${CONFIG_LOCATION}/matplotlib"
mkdir -p "${CONFIG_LOCATION}/xmenu"
mkdir -p "${CONFIG_LOCATION}/wal-discord"

ln -sf "${wal_cache_loc}/colors.Xresources"   "${HOME}/.Xresources"
ln -sf "${wal_cache_loc}/custom-rofi.rasi"    "${CONFIG_LOCATION}/rofi/config.rasi"
ln -sf "${wal_cache_loc}/dunstrc"             "${CONFIG_LOCATION}/dunst/dunstrc"
ln -sf "${wal_cache_loc}/glava_bars.glsl"     "${CONFIG_LOCATION}/glava/glava_bars.glsl"
ln -sf "${wal_cache_loc}/glava_circle.glsl"   "${CONFIG_LOCATION}/glava/glava_circle.glsl"
ln -sf "${wal_cache_loc}/glava_graph.glsl"    "${CONFIG_LOCATION}/glava/glava_graph.glsl"
ln -sf "${wal_cache_loc}/glava_main.glsl"     "${CONFIG_LOCATION}/glava/glava_main.glsl"
ln -sf "${wal_cache_loc}/glava_radial.glsl"   "${CONFIG_LOCATION}/glava/glava_radial.glsl"
ln -sf "${wal_cache_loc}/glava_wave.glsl"     "${CONFIG_LOCATION}/glava/glava_wave.glsl"
ln -sf "${wal_cache_loc}/matplotlibrc"        "${CONFIG_LOCATION}/matplotlib/matplotlibrc"
ln -sf "${wal_cache_loc}/zathurarc"           "${CONFIG_LOCATION}/zathura/zathurarc"
ln -sf "${wal_cache_loc}/xmenu-config.h"      "${CONFIG_LOCATION}/xmenu/colors-xmenu.h"
ln -sf "${wal_cache_loc}/colors.scss"         "${CONFIG_LOCATION}/wal-discord/colors.scss"
