#!/usr/bin/env bash

source "${HOME}/Singularis/bin/common"
source "${HOME}/Singularis/bin/variables"

log_info "Installing wal"

ln -sf "${CONFIG}/wal" "${CONFIG_LOCATION}"

log_info "Syncing templates"

wal_cache_loc="${HOME}/.cache/wal"

ln -sf "${wal_cache_loc}/custom-rofi.rasi"    "${HOME}/.config/rofi/config.rasi"
ln -sf "${wal_cache_loc}/dunstrc"             "${HOME}/.config/dunst/dunstrc"
ln -sf "${wal_cache_loc}/glava_bars.glsl"     "${HOME}/.config/glava/glava_bars.glsl"
ln -sf "${wal_cache_loc}/glava_circle.glsl"   "${HOME}/.config/glava/glava_circle.glsl"
ln -sf "${wal_cache_loc}/glava_graph.glsl"    "${HOME}/.config/glava/glava_graph.glsl"
ln -sf "${wal_cache_loc}/glava_main.glsl"     "${HOME}/.config/glava/glava_main.glsl"
ln -sf "${wal_cache_loc}/glava_radial.glsl"   "${HOME}/.config/glava/glava_radial.glsl"
ln -sf "${wal_cache_loc}/glava_wave.glsl"     "${HOME}/.config/glava/glava_wave.glsl"
ln -sf "${wal_cache_loc}/matplotlibrc"        "${HOME}/.config/matplotlib/matplotlibrc"
ln -sf "${wal_cache_loc}/zathurarc"           "${HOME}/.config/zathura/zathurarc"
ln -sf "${wal_cache_loc}/xmenu-config.h"      "${HOME}/.config/xmenu/colors-xmenu.h"
ln -sf "${wal_cache_loc}/colors.scss"         "${HOME}/.config/wal-discord/colors.scss"
