return {
  settings = {
    tsserver_plugins = {
      "@styled/typescript-styled-plugin",
    },
    publish_diagnostic_on = "change",
    typescript = {
      tsserver_file_preferences = {
        includeInlayEnumMemberValueHints = true,
        includeInlayFunctionLikeReturnTypeHints = true,
        includeInlayFunctionParameterTypeHints = true,
        includeInlayParameterNameHints = "all",
        includeInlayParameterNameHintsWhenArgumentMatchesName = true,
        includeInlayPropertyDeclarationTypeHints = true,
        includeInlayVariableTypeHints = true,
      },
      format = {
        semicolons = "insert",
        convertTabsToSpaces = false,
        insertSpaceAfterCommaDelimiter = true,
        insertSpaceAfterConstructor = true,
        insertSpaceAfterFunctionKeywordForAnonymousFunctions = true,
        insertSpaceAfterKeywordsInControlFlowStatements = true,
        insertSpaceAfterOpeningAndBeforeClosingEmptyBraces = true,
        insertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces = true,
        insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces = true,
        insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets = true,
        insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis = true,
        insertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces = true,
        insertSpaceAfterSemicolonInForStatements = true,
        insertSpaceAfterTypeAssertion = true,
        insertSpaceBeforeAndAfterBinaryOperators = true,
        insertSpaceBeforeFunctionParenthesis = true,
        insertSpaceBeforeTypeAnnotation = true,
        placeOpenBraceOnNewLineForControlBlocks = true,
        placeOpenBraceOnNewLineForFunctions = true,
        trimTrailingWhitespace = true,
      },
    },
  },
  install = true,
}
